In [1]:
import numpy as np

In [2]:
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]

In [10]:
a = [[1,2],[3,4]]

b = [[5,6],[7,8]]

In [12]:
# Concatenar listas
array = np.concatenate((x, y, z))
print(array)

[1 2 3 1 2 3 1 2 3]


In [14]:
array2 = np.concatenate((a,b), axis=1)
print(array2)
print(array2.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [16]:
array3 = np.concatenate((a,b), axis=0)
print(array3)
print(f"Shape: {array3.shape}")

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)


In [ ]:
array3.reshape(2, 4) # Redimensionar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
array_sumada = array3 + array3
print(array_sumada)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [20]:
array_sumada = array_sumada * 20
print(array_sumada)

[[ 40  80]
 [120 160]
 [200 240]
 [280 320]]


In [21]:
racies = np.sqrt(array_sumada)
print(racies)

[[ 6.32455532  8.94427191]
 [10.95445115 12.64911064]
 [14.14213562 15.49193338]
 [16.73320053 17.88854382]]


### Ejercicios

In [29]:
import numpy as np

array1 = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

array_concatenado = np.concatenate((array1, array2))
print(array_concatenado)

[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
import numpy as np

array_original = np.array([1,2,3,4,5,6])
array_reshaped = array_original.reshape(2, 3)
print(array_reshaped)

[[1 2 3]
 [4 5 6]]


In [32]:
import numpy as np

A = np.array(
    [[1,2], 
    [3,4]]
)
B = np.array(
    [[5,6], 
    [7,8]]
)

suma_AB = A + B
print(suma_AB)

producto_AB = A * B
print(producto_AB)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
